version: "3"

services:
  web:
    environment:
      - DJANGO_SETTINGS_MODULE=apps.settings
    build: .
    command: sh -c "python3 dao.py &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
   
