# Generated by Django 4.2.11 on 2024-04-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('uid', models.AutoField(db_column='UID', primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, db_column='Version', max_length=255, null=True)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=255, null=True)),
                ('description_html', models.TextField(blank=True, db_column='DescriptionHtml', null=True)),
                ('image_url', models.CharField(blank=True, db_column='ImageURL', max_length=255, null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('edit_modify_date', models.DateTimeField(blank=True, db_column='EditModifyDate', null=True)),
                ('start_date', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('end_date', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('hit_rate', models.IntegerField(blank=True, db_column='HitRate', null=True)),
                ('category_id', models.IntegerField(blank=True, db_column='CategoryID', null=True)),
                ('website_id', models.IntegerField(blank=True, db_column='WebsiteID', null=True)),
                ('location_id', models.IntegerField(blank=True, db_column='LocationID', null=True)),
                ('ticket_id', models.IntegerField(blank=True, db_column='TicketID', null=True)),
            ],
            options={
                'db_table': 'Campaign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignLocationInfo',
            fields=[
                ('location_id', models.AutoField(db_column='LocationID', primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, db_column='Location', max_length=255, null=True)),
                ('location_name', models.CharField(blank=True, db_column='LocationName', max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, db_column='Latitude', decimal_places=5, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, db_column='Longitude', decimal_places=5, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Campaign_Location_Info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignUnitRelation',
            fields=[
                ('relation_id', models.AutoField(db_column='RelationID', primary_key=True, serialize=False)),
                ('campaign_id', models.IntegerField(blank=True, db_column='CampaignID', null=True)),
                ('unit_id', models.IntegerField(blank=True, db_column='UnitID', null=True)),
                ('relation_type', models.CharField(blank=True, db_column='RelationType', max_length=255, null=True)),
            ],
            options={
                'db_table': 'CampaignUnitRelation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(db_column='CategoryID', primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, db_column='CategoryName', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('action_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(db_column='TicketID', primary_key=True, serialize=False)),
                ('on_sales', models.BooleanField(blank=True, db_column='OnSales', null=True)),
                ('discount_info', models.CharField(blank=True, db_column='DiscountInfo', max_length=255, null=True)),
                ('price_description', models.CharField(blank=True, db_column='Price', max_length=255, null=True)),
                ('end_time', models.DateTimeField(blank=True, db_column='EndTime', null=True)),
            ],
            options={
                'db_table': 'Ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unitid', models.AutoField(db_column='UnitID', primary_key=True, serialize=False)),
                ('unitname', models.CharField(blank=True, db_column='UnitName', max_length=255, null=True)),
                ('unittype', models.CharField(blank=True, db_column='UnitType', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Unit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('websiteid', models.AutoField(db_column='WebsiteID', primary_key=True, serialize=False)),
                ('websales', models.CharField(blank=True, db_column='WebSales', max_length=255, null=True)),
                ('sourcewebpromote', models.CharField(blank=True, db_column='SourceWebPromote', max_length=255, null=True)),
                ('sourcewebname', models.CharField(blank=True, db_column='SourceWebName', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Website',
                'managed': False,
            },
        ),
    ]
