# Generated by Django 4.2.11 on 2024-04-08 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('uid', models.CharField(blank=True, db_column='UID', max_length=255, primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, db_column='Version', max_length=255, null=True)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=255, null=True)),
                ('description_html', models.TextField(blank=True, db_column='DescriptionHtml', null=True)),
                ('image_url', models.CharField(blank=True, db_column='ImageURL', max_length=255, null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('edit_modify_date', models.DateTimeField(blank=True, db_column='EditModifyDate', null=True)),
                ('start_date', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('end_date', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('hit_rate', models.IntegerField(blank=True, db_column='HitRate', null=True)),
            ],
            options={
                'db_table': 'Campaign',
            },
        ),
        migrations.CreateModel(
            name='CampaignLocationInfo',
            fields=[
                ('location_id', models.AutoField(db_column='LocationID', primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, db_column='Location', max_length=255, null=True)),
                ('location_name', models.CharField(blank=True, db_column='LocationName', max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, db_column='Latitude', decimal_places=5, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, db_column='Longitude', decimal_places=5, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'CampaignLocationInfo',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(db_column='CategoryID', primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, db_column='CategoryName', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(db_column='TicketID', primary_key=True, serialize=False)),
                ('on_sales', models.BooleanField(blank=True, db_column='OnSales', null=True)),
                ('discount_info', models.CharField(blank=True, db_column='DiscountInfo', max_length=255, null=True)),
                ('price_description', models.CharField(blank=True, db_column='Price', max_length=255, null=True)),
                ('end_time', models.DateTimeField(blank=True, db_column='EndTime', null=True)),
            ],
            options={
                'db_table': 'Ticket',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unitid', models.AutoField(db_column='UnitID', primary_key=True, serialize=False)),
                ('unitname', models.CharField(blank=True, db_column='UnitName', max_length=255, null=True)),
                ('unittype', models.CharField(blank=True, choices=[('subUnit', 'Sub Unit'), ('masterUnit', 'Master Unit'), ('supportUnit', 'Support Unit'), ('showUnit', 'Show Unit'), ('otherUnit', 'Other Unit')], db_column='UnitType', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Unit',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('websiteid', models.AutoField(db_column='WebsiteID', primary_key=True, serialize=False)),
                ('websales', models.CharField(blank=True, db_column='WebSales', max_length=255, null=True)),
                ('sourcewebpromote', models.CharField(blank=True, db_column='SourceWebPromote', max_length=255, null=True)),
                ('sourcewebname', models.CharField(blank=True, db_column='SourceWebName', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Website',
            },
        ),
        migrations.CreateModel(
            name='CampaignUnitRelation',
            fields=[
                ('relation_id', models.AutoField(db_column='RelationID', primary_key=True, serialize=False)),
                ('relation_type', models.CharField(blank=True, db_column='RelationType', max_length=255, null=True)),
                ('campaign', models.ForeignKey(blank=True, db_column='UID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.campaign')),
                ('unit', models.ForeignKey(blank=True, db_column='UnitID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.unit')),
            ],
            options={
                'db_table': 'CampaignUnitRelation',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.ForeignKey(blank=True, db_column='CategoryID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='location',
            field=models.ForeignKey(blank=True, db_column='LocationID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.campaignlocationinfo'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ticket',
            field=models.ForeignKey(blank=True, db_column='TicketID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ticket'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='website',
            field=models.ForeignKey(blank=True, db_column='WebsiteID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.website'),
        ),
    ]
