# Generated by Django 4.2.11 on 2024-04-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_campaign_category_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignlocationinfo',
            old_name='address',
            new_name='location',
        ),
    ]
