# Generated by Django 4.2.11 on 2024-04-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_address_campaignlocationinfo_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='sourcewebname',
            new_name='source_web_name',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='sourcewebpromote',
            new_name='source_web_promote',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='websales',
            new_name='web_sales',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='websiteid',
            new_name='website_id',
        ),
    ]
